### ISSUE TITLE
There are some undefined index notices which break the development mode

### ISSUE THREAD

**Issue by Kostanos** [magento-hackathon/Sandfox_GeoIP#11]
```
Notice: Uninitialized string offset: 0  in /var/www/testing/LoftyCode/lib/geoip/app/code/community/Openstream/GeoIP/Model/Wrapper.php on line 302

#0 /var/www/testing/LoftyCode/lib/geoip/app/code/community/Openstream/GeoIP/Model/Wrapper.php(302): mageCoreErrorHandler(8, 'Uninitialized s...', '/var/www/testin...', 302, Array)
#1 /var/www/testing/LoftyCode/lib/geoip/app/code/community/Openstream/GeoIP/Model/Wrapper.php(273): Openstream_GeoIP_Model_Wrapper->_geoip_seek_country(/*IP hash here*/)
#2 /var/www/testing/LoftyCode/lib/geoip/app/code/community/Openstream/GeoIP/Model/Wrapper.php(267): Openstream_GeoIP_Model_Wrapper->geoip_country_id_by_addr('some_ip_here')
#3 /var/www/testing/LoftyCode/lib/geoip/app/code/community/Openstream/GeoIP/Model/Country.php(22): Openstream_GeoIP_Model_Wrapper->geoip_country_code_by_addr('some_ip_here')
#4 /var/www/testing/LoftyCode/lib/geoip/app/code/community/Openstream/GeoIP/Model/Country.php(12): Openstream_GeoIP_Model_Country->getCountryByIp('some_ip_here')
#5 /var/www/testing/LoftySite/magento/app/code/core/Mage/Core/Model/Config.php(1348): Openstream_GeoIP_Model_Country->__construct(Array)
#6 /var/www/testing/LoftySite/magento/app/Mage.php(463): Mage_Core_Model_Config->getModelInstance('geoip/country', Array)
#7 /var/www/testing/LoftyCode/lib/geoip/app/code/community/Openstream/GeoIP/Model/Observer.php(7): Mage::getModel('geoip/country')
#8 /var/www/testing/LoftySite/magento/app/code/core/Mage/Core/Model/App.php(1338): Openstream_GeoIP_Model_Observer->controllerFrontInitBefore(Object(Varien_Event_Observer))
#9 /var/www/testing/LoftySite/magento/app/code/core/Mage/Core/Model/App.php(1317): Mage_Core_Model_App->_callObserverMethod(Object(Openstream_GeoIP_Model_Observer), 'controllerFront...', Object(Varien_Event_Observer))
#10 /var/www/testing/LoftySite/magento/app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('controller_fron...', Array)
#11 /var/www/testing/LoftySite/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(128): Mage::dispatchEvent('controller_fron...', Array)
#12 /var/www/testing/LoftySite/magento/app/code/core/Mage/Core/Model/App.php(749): Mage_Core_Controller_Varien_Front->init()
#13 /var/www/testing/LoftySite/magento/app/code/core/Mage/Core/Model/App.php(1094): Mage_Core_Model_App->_initFrontController()
#14 /var/www/testing/LoftySite/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Model_App->getFrontController()
#15 /var/www/testing/LoftySite/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#16 /var/www/testing/LoftySite/magento/index.php(87): Mage::run('', 'store')
#17 {main}
```

**Comment by sprankhub** [comment]
Closed because of missing feedback.
